services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro

  lego-acme:
    image: eryshev/lego-cron-wrapper
    container_name: lego-acme
    command: >
      --accept-tos --email=user@gmail.com --dns selectelv2
      --domains=*.status.sales.company.org --domains=status.sales.company.org --domains=*.ref.sales.company.org --domains=ref.sales.company.org
    environment:
      - RUN_ARGUMENTS=--run-hook=/app/deploy
      - RENEW_ARGUMENTS=--renew-hook=/app/deploy
      - SELECTELV2_USERNAME=needtofill
      - SELECTELV2_PASSWORD=needtofill
      - SELECTELV2_ACCOUNT_ID=needtofill
      - SELECTELV2_PROJECT_ID=needtofill
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/app/certificates
      - ./deploy.sh:/app/deploy

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    environment:
      - VIRTUAL_HOST=status.sales.company.org
    depends_on:
      - backend
      - nginx-proxy

  referral:
    build: ./referral
    container_name: referral
    restart: always
    environment:
      - VIRTUAL_HOST=ref.sales.company.org
    depends_on:
      - nginx-proxy

  backend:
    build: ./backend
    container_name: backend
    restart: always
    command: gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - VIRTUAL_PORT=8000
      - VIRTUAL_HOST=api.status.sales.company.org
    depends_on:
      - nginx-proxy

volumes:
  certs: