services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=example.com

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy
    environment:
      DEFAULT_EMAIL: 'example@gmail.com'
    depends_on:
      - nginx-proxy

  backend:
    build:
      context: ./path/to/backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      VIRTUAL_HOST: 'api.example.com'
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: 'api.example.com'
      LETSENCRYPT_EMAIL: 'example@gmail.com'
    depends_on:
      - nginx-proxy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      VIRTUAL_HOST: 'example.com'
      LETSENCRYPT_HOST: 'example.com'
      LETSENCRYPT_EMAIL: 'example@gmail.com'
    depends_on:
      - nginx-proxy

volumes:
  certs:
  vhost:
  html:
  acme:
