"""Add relationship between user and status

Revision ID: 20527eba50e7
Revises: be58f79435a6
Create Date: 2024-05-26 20:57:10.459306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20527eba50e7'
down_revision: Union[str, None] = 'be58f79435a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_user_status_id'), 'user', ['status_id'], unique=False)
    op.create_foreign_key(None, 'user', 'status', ['status_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_status_id'), table_name='user')
    op.alter_column('user', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
