"""Add priority to Status model

Revision ID: 4f6dd67afea0
Revises: 50589cde20fc
Create Date: 2024-05-28 15:32:34.658101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6dd67afea0'
down_revision: Union[str, None] = '50589cde20fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'priority')
    # ### end Alembic commands ###
