"""Add is_manager column

Revision ID: b2cd48bc0e95
Revises: 576e18c70852
Create Date: 2024-05-26 00:39:14.218346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2cd48bc0e95'
down_revision: Union[str, None] = '576e18c70852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_manager', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_manager')
    # ### end Alembic commands ###
