"""Added mango_user_id column to user table

Revision ID: 41ffd096a143
Revises: 8211a510b637
Create Date: 2024-06-21 13:56:09.617537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ffd096a143'
down_revision: Union[str, None] = '8211a510b637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mango_user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['mango_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'mango_user_id')
    # ### end Alembic commands ###
