"""Add busy_time table and index for foreign keys

Revision ID: be58f79435a6
Revises: b2cd48bc0e95
Create Date: 2024-05-26 12:35:05.701116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be58f79435a6'
down_revision: Union[str, None] = 'b2cd48bc0e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busy_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_busy_time_status_id'), 'busy_time', ['status_id'], unique=False)
    op.create_index(op.f('ix_busy_time_user_id'), 'busy_time', ['user_id'], unique=True)
    op.create_index(op.f('ix_comment_owner_id'), 'comment', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_owner_id'), table_name='comment')
    op.drop_index(op.f('ix_busy_time_user_id'), table_name='busy_time')
    op.drop_index(op.f('ix_busy_time_status_id'), table_name='busy_time')
    op.drop_table('busy_time')
    # ### end Alembic commands ###
