"""Add is_account_manager to User model

Revision ID: 8211a510b637
Revises: 4f6dd67afea0
Create Date: 2024-05-31 11:43:29.704821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8211a510b637'
down_revision: Union[str, None] = '4f6dd67afea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_account_manager', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_account_manager')
    # ### end Alembic commands ###
