"""add_telegram_chat_id_column

Revision ID: af4a61f6f25f
Revises: bcf9827a6f70
Create Date: 2025-10-22 14:38:01.028266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af4a61f6f25f"
down_revision: Union[str, None] = "bcf9827a6f70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("telegram_chat_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "telegram_chat_id")
    # ### end Alembic commands ###
