"""Add is_cc_manager to User model

Revision ID: 59fecee6466f
Revises: b0c9a057f5d8
Create Date: 2025-07-15 22:41:29.586788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59fecee6466f"
down_revision: Union[str, None] = "b0c9a057f5d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_cc_manager", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_cc_manager")
    # ### end Alembic commands ###
