"""change_duration_minutes_to_seconds

Revision ID: 0f4b11caa3c3
Revises: 3c1dbf6b5c50
Create Date: 2025-10-27 16:22:10.164219

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f4b11caa3c3"
down_revision: Union[str, None] = "3c1dbf6b5c50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Переименовываем колонку duration_minutes в duration_seconds
    op.alter_column(
        "status_history", "duration_minutes", new_column_name="duration_seconds"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем обратно duration_seconds в duration_minutes
    op.alter_column(
        "status_history", "duration_seconds", new_column_name="duration_minutes"
    )
    # ### end Alembic commands ###
