"""add_status_history_table

Revision ID: 3c1dbf6b5c50
Revises: af4a61f6f25f
Create Date: 2025-10-27 15:09:29.467497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1dbf6b5c50'
down_revision: Union[str, None] = 'af4a61f6f25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old_status_id', sa.Integer(), nullable=True),
    sa.Column('new_status_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['new_status_id'], ['status.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['old_status_id'], ['status.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_new_status_id'), 'status_history', ['new_status_id'], unique=False)
    op.create_index(op.f('ix_status_history_user_id'), 'status_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_history_user_id'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_new_status_id'), table_name='status_history')
    op.drop_table('status_history')
    # ### end Alembic commands ###
