"""add_telegram_chat_id_to_user_table

Revision ID: bcf9827a6f70
Revises: 59fecee6466f
Create Date: 2025-10-22 14:37:04.799395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf9827a6f70'
down_revision: Union[str, None] = '59fecee6466f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
